### PR TITLE
Ensure sequential `push` calls will trigger correct updates

### PR DESCRIPTION
**Pull request by scottrippey**
Fixes https://github.com/scottrippey/next-router-mock/pull/12

### CODE REVIEW

**Comment by scottrippey** [comment]
@icyjoseph Would you mind taking a look at this, to see if it sounds like an appropriate fix for #12 ?

**Comment by icyJoseph** [comment]
Hi,

I was actually looking at it. 

This does seem to do the trick. I like the new naming and tests as well.

Looking forward to try it out on my main project.

**Review by icyJoseph — APPROVED** [review]
LGTM

**Comment by scottrippey** [comment]
Thanks! It took me a while to realize the differences between the `singletonRouter` and the `useRouter` hook, but now that I named things more clearly it's a lot easier to understand.  Will merge!

**Comment by scottrippey** [comment]
Published as `0.3.2`

**Pull request merged**
