### PR TITLE
Use Mitt events to avoid warnings

### PR DESCRIPTION
**Pull request by scottrippey**
When rendering 10+ links, the native `events` module spits out a `MaxListeners` warning.

This PR switches to using `mitt`, which is the same library that Next uses, and does not have the `MaxListeners` warnings.

### CODE REVIEW

**Comment by scottrippey** [comment]
@pgmanutd Mind reviewing?

**Comment by pgmanutd** [comment]
> @pgmanutd Mind reviewing?

Cool! Looks good to me :)

**Comment by pgmanutd** [comment]
@scottrippey: Are we merging this one?

**Comment by scottrippey** [comment]
Published as `0.2.4` 👍

**Comment by pgmanutd** [comment]
@scottrippey: Thanks for the latest version. It works seamlessly. All the tests are passing (with 0 warnings) and I also removed `mitt` dependency. [Here is the change](https://github.com/Open-Speech-EkStep/crowdsource-dataplatform/commit/dbf321f1214d0c0ae81bd086d4ed1b813a039f82) if it helps anyone.

**Pull request merged**
